#pragma once
#include "SDK Stuff.h"
#include "Interface.h"
#include "Math.h"
#include <iostream>

class EntityStuff
{
public:
	Math oMath;

	IClientEntity* pLocalPlayer;
	EntityStuff()
	{
		pLocalPlayer = (IClientEntity*)CInterfaces::pEntityList->GetClientEntity(CInterfaces::pEngine->GetLocalPlayer());
	}

	IClientEntity* GrabClosestEnt();
	bool IsValid(IClientEntity* ent);
	int GrabBone(IClientEntity* ent, const char* boneName);
	Vector GetBonePos(IClientEntity* ent, int boneIndex);
	void TestStuff(IClientEntity* ent);


	const char* boneArray[19] = {
		"ValveBiped.Bip01_Pelvis",
		"ValveBiped.Bip01_L_Thigh",
		"ValveBiped.Bip01_L_Calf",
		"ValveBiped.Bip01_L_Foot",
		"ValveBiped.Bip01_L_Toe0",
		"ValveBiped.Bip01_R_Thigh",
		"ValveBiped.Bip01_R_Calf",
		"ValveBiped.Bip01_R_Foot",
		"ValveBiped.Bip01_R_Toe0",
		"ValveBiped.Bip01_Spine1",
		"ValveBiped.Bip01_Spine2",
		"ValveBiped.Bip01_Neck1",
		"ValveBiped.Bip01_Head1",
		"ValveBiped.Bip01_L_UpperArm",
		"ValveBiped.Bip01_L_Forearm",
		"ValveBiped.Bip01_L_Hand",
		"ValveBiped.Bip01_R_UpperArm",
		"ValveBiped.Bip01_R_Forearm" };

    enum ClassIDs
    {
        CPropCannon = 0,
        CWeaponBinoculars = 0,
        CWeaponHopwire = 0,
        CWeaponGaussGun = 0,
        CPlasmaBeamNode = 0,
        AR2Explosion = 0,
        CFlaregun = 0,
        CAI_BaseNPC = 1,
        CAlyxEmpEffect = 2,
        CBaseAnimating = 3,
        CBaseAnimatingOverlay = 4,
        CBaseCombatCharacter = 5,
        CBaseCombatWeapon = 6,
        CBaseDoor = 7,
        CBaseEntity = 8,
        CBaseFlex = 9,
        CBaseGrenade = 10,
        CBaseHelicopter = 11,
        CBaseHelicopter_HL1 = 12,
        CBaseHL1CombatWeapon = 13,
        CBaseHL1MPCombatWeapon = 14,
        CBaseHL2MPBludgeonWeapon = 15,
        CBaseHL2MPCombatWeapon = 16,
        CBaseHLBludgeonWeapon = 17,
        CBaseHLCombatWeapon = 18,
        CBaseParticleEntity = 19,
        CBasePlayer = 20,
        CBasePropDoor = 21,
        CBaseTempEntity = 22,
        CBaseViewModel = 23,
        CBeam = 24,
        CBeamSpotlight = 25,
        CBoneFollower = 26,
        CBoneManipulate = 27,
        CBreakableProp = 28,
        CBreakableSurface = 29,
        CCitadelEnergyCore = 30,
        CColorCorrection = 31,
        CColorCorrectionVolume = 32,
        CCorpse = 33,
        CCrossbowBolt = 34,
        CDynamicLight = 35,
        CDynamicProp = 36,
        CEmbers = 37,
        CEntityDissolve = 38,
        CEntityFlame = 39,
        CEntityParticleTrail = 40,
        CEnvDetailController = 41,
        CEnvHeadcrabCanister = 42,
        CEnvParticleScript = 43,
        CEnvProjectedTexture = 44,
        CEnvQuadraticBeam = 45,
        CEnvScreenEffect = 46,
        CEnvScreenOverlay = 47,
        CEnvStarfield = 48,
        CEnvTonemapController = 49,
        CEnvWind = 50,
        CFireSmoke = 51,
        CFireTrail = 52,
        CFish = 53,
        CFlare = 54,
        CFleshEffectTarget = 55,
        CFlexManipulate = 56,
        CFogController = 57,
        CFunc_Dust = 58,
        CFunc_LOD = 59,
        CFuncAreaPortalWindow = 60,
        CFuncConveyor = 61,
        CFuncLadder = 62,
        CFuncMonitor = 63,
        CFuncOccluder = 64,
        CFuncReflectiveGlass = 65,
        CFuncRotating = 66,
        CFuncSmokeVolume = 67,
        CFuncTrackTrain = 68,
        CGameRulesProxy = 69,
        CGMOD_Player = 70,
        CGMODGameRulesProxy = 71,
        CHandleTest = 72,
        CHL2_Player = 73,
        CHL2MP_Player = 74,
        CHL2MPGameRulesProxy = 75,
        CHL2MPMachineGun = 76,
        CHL2MPRagdoll = 77,
        CHLMachineGun = 78,
        CHLSelectFireMachineGun = 79,
        CInfoLadderDismount = 80,
        CInfoLightingRelative = 81,
        CInfoOverlayAccessor = 82,
        CInfoTeleporterCountdown = 83,
        CLaserDot = 84,
        CLaserDot_HL1 = 85,
        CLightGlow = 86,
        CLuaNextBot = 87,
        CMaterialModifyControl = 88,
        CMortarShell = 89,
        CNPC_AntlionGuard = 90,
        CNPC_Barnacle = 91,
        CNPC_Barney = 92,
        CNPC_CombineGunship = 93,
        CNPC_Manhack = 94,
        CNPC_Puppet = 95,
        CNPC_RollerMine = 96,
        CNPC_Strider = 97,
        CNPC_Vortigaunt = 98,
        CParticleFire = 99,
        CParticlePerformanceMonitor = 100,
        CParticleSystem = 101,
        CPhysBeam = 102,
        CPhysBox = 103,
        CPhysBoxMultiplayer = 104,
        CPhysicsProp = 105,
        CPhysicsPropMultiplayer = 106,
        CPhysMagnet = 107,
        CPlasma = 108,
        CPlayerResource = 109,
        CPointCamera = 110,
        CPointCommentaryNode = 111,
        CPoseController = 112,
        CPrecipitation = 113,
        CPredictedViewModel = 114,
        CPropAirboat = 115,
        CPropCombineBall = 116,
        CPropCrane = 117,
        CPropDoorRotating = 118,
        CPropJeep = 119,
        CPropJeepEpisodic = 120,
        CPropScalable = 121,
        CPropVehicleChoreoGeneric = 122,
        CPropVehicleDriveable = 123,
        CPropVehiclePrisonerPod = 124,
        CRagdollManager = 125,
        CRagdollProp = 126,
        CRagdollPropAttached = 127,
        CRopeKeyframe = 128,
        CRotorWashEmitter = 129,
        CRpgRocket = 130,
        CSceneEntity = 131,
        CScriptIntro = 132,
        CSENT_AI = 133,
        CSENT_anim = 134,
        CSENT_point = 135,
        CShadowControl = 136,
        CSlideshowDisplay = 137,
        CSmokeStack = 138,
        CSpotlightEnd = 139,
        CSprite = 140,
        CSpriteOriented = 141,
        CSpriteTrail = 142,
        CSteamJet = 143,
        CSun = 144,
        CTeam = 145,
        CTEAntlionDust = 146,
        CTEArmorRicochet = 147,
        CTEBaseBeam = 148,
        CTEBeamEntPoint = 149,
        CTEBeamEnts = 150,
        CTEBeamFollow = 151,
        CTEBeamLaser = 152,
        CTEBeamPoints = 153,
        CTEBeamRing = 154,
        CTEBeamRingPoint = 155,
        CTEBeamSpline = 156,
        CTEBloodSprite = 157,
        CTEBloodStream = 158,
        CTEBreakModel = 159,
        CTEBSPDecal = 160,
        CTEBubbles = 161,
        CTEBubbleTrail = 162,
        CTEClientProjectile = 163,
        CTEConcussiveExplosion = 164,
        CTEDecal = 165,
        CTEDust = 166,
        CTEDynamicLight = 167,
        CTEEffectDispatch = 168,
        CTEEnergySplash = 169,
        CTEExplosion = 170,
        CTEFizz = 171,
        CTEFootprintDecal = 172,
        CTEGaussExplosion = 173,
        CTEGlowSprite = 174,
        CTEHL2MPFireBullets = 175,
        CTEImpact = 176,
        CTEKillPlayerAttachments = 177,
        CTELargeFunnel = 178,
        CTEMetalSparks = 179,
        CTEMuzzleFlash = 180,
        CTEParticleSystem = 181,
        CTEPhysicsProp = 182,
        CTEPlayerAnimEvent = 183,
        CTEPlayerDecal = 184,
        CTEProjectedDecal = 185,
        CTEShatterSurface = 186,
        CTEShowLine = 187,
        CTesla = 188,
        CTESmoke = 189,
        CTESparks = 190,
        CTESprite = 191,
        CTESpriteSpray = 192,
        CTest_ProxyToggle_Networkable = 193,
        CTestTraceline = 194,
        CTEWorldDecal = 195,
        CVGuiScreen = 196,
        CVortigauntChargeToken = 197,
        CVortigauntEffectDispel = 198,
        CVoteController = 199,
        CWaterBullet = 200,
        CWaterLODControl = 201,
        CWeapon357 = 202,
        CWeapon357_HL1 = 203,
        CWeapon_SLAM = 204,
        CWeaponAlyxGun = 205,
        CWeaponAnnabelle = 206,
        CWeaponAR2 = 207,
        CWeaponBugBait = 208,
        CWeaponCitizenPackage = 209,
        CWeaponCitizenSuitcase = 210,
        CWeaponCrossbow = 211,
        CWeaponCrossbow_HL1 = 212,
        CWeaponCrowbar = 213,
        CWeaponCrowbar_HL1 = 214,
        CWeaponCubemap = 215,
        CWeaponCycler = 216,
        CWeaponEgon = 217,
        CWeaponFrag = 218,
        CWeaponGauss = 219,
        CWeaponGlock = 220,
        CWeaponHandGrenade = 221,
        CWeaponHgun = 222,
        CWeaponHL2MPBase = 223,
        CWeaponMP5 = 224,
        CWeaponOldManHarpoon = 225,
        CWeaponPhysCannon = 226,
        CWeaponPhysGun = 227,
        CWeaponPistol = 228,
        CWeaponRPG = 229,
        CWeaponRPG_HL1 = 230,
        CWeaponSatchel = 231,
        CWeaponShotgun = 232,
        CWeaponShotgun_HL1 = 233,
        CWeaponSMG1 = 234,
        CWeaponSnark = 235,
        CWeaponStunStick = 236,
        CWeaponSWEP = 237,
        CWeaponTripMine = 238,
        CWorld = 239,
        DustTrail = 240,
        MovieExplosion = 241,
        NextBotCombatCharacter = 242,
        ParticleSmokeGrenade = 243,
        RocketTrail = 244,
        SmokeTrail = 245,
        SporeExplosion = 246,
        SporeTrail = 247,
    };
};
